name: Compile Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            unzip \
            zip

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade Cython==0.29.33 buildozer

    - name: Install Android SDK build-tools 33 y aceptar licencias
      run: |
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q cmdline-tools.zip
        mv cmdline-tools latest
        SDKMANAGER=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager
        yes | $SDKMANAGER --licenses --sdk_root=$ANDROID_SDK_ROOT
        $SDKMANAGER --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0"
        mkdir -p $ANDROID_SDK_ROOT/tools/bin
        ln -sf $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/* $ANDROID_SDK_ROOT/tools/bin/

    - name: Forzar Python 3.10 como python/python3 del sistema
      run: |
        PYBIN=$(dirname $(which python3))
        sudo ln -sf $PYBIN/python3 /usr/bin/python3
        sudo ln -sf $PYBIN/python3 /usr/bin/python
        python3 --version

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
